services:
  web:
    container_name: ddf-shuffle
    build: .
    ports:
      - "8084:8084/tcp"
    environment:
      TZ: 'Europe/Berlin'
      SPOTIFY_SHUFFLE_PORT: 8084
      SPOTIFY_SHUFFLE_CLIENT_ID: 
      SPOTIFY_SHUFFLE_CLIENT_SECRET: 
      SPOTIFY_SHUFFLE_ARTIST_ID: 3meJIgRw7YleJrmbpbJK6S
      SPOTIFY_SHUFFLE_SHOW_ID: 5cgMSSNAioVK0STCTlvo0z
      SPOTIFY_SHUFFLE_ARTIST_NAME: Die drei Fragezeichen
      SPOTIFY_SHUFFLE_MAX_LOG_SIZE: 10000000
      SPOTIFY_SHUFFLE_LOG_META: "false"
    restart: unless-stopped


